services:
  - type: web
    name: supply-chain-tracker-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: PORT
        value: 3001
      - key: BASE_SEPOLIA_RPC_URL
        sync: false
      - key: PRIVATE_KEY
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: PINATA_JWT
        sync: false
      - key: PINATA_GATEWAY
        sync: false
